import { default as pluginStylistic } from '@stylistic/eslint-plugin';
import type { FlatConfig } from '../types';

export function stylistic (): FlatConfig {
  return [
    {
      name: 'hellolin/stylistic/rules',
      plugins: {
        style: pluginStylistic,
      },
      rules: {
        'style/arrow-parens': ['error', 'as-needed'],
        'style/arrow-spacing': 'error',
        'style/block-spacing': 'error',
        'style/brace-style': ['error', '1tbs'],
        'style/comma-dangle': ['error', 'always-multiline'],
        'style/comma-spacing': 'error',
        'style/comma-style': ['error', 'last'],
        'style/curly-newline': 'error',
        'style/dot-location': ['error', 'property'],
        'style/eol-last': 'error',
        'style/function-call-argument-newline': ['error', 'consistent'],
        'style/function-call-spacing': ['error', 'never'],
        'style/function-paren-newline': ['error', 'consistent'],
        'style/generator-star-spacing': 'error',
        'style/indent': ['error', 2, {
          SwitchCase: 0,
          VariableDeclarator: 'first',
          offsetTernaryExpressions: true,
        }],
        'style/indent-binary-ops': ['error', 2],
        'style/jsx-closing-bracket-location': ['error', 'tag-aligned'],
        'style/jsx-closing-tag-location': ['error', 'tag-aligned'],
        'style/jsx-equals-spacing': ['error', 'never'],
        'style/jsx-indent-props': ['error', 2],
        'style/jsx-pascal-case': ['warn', { allowNamespace: true }],
        'style/jsx-props-no-multi-spaces': 'error',
        'style/jsx-quotes': ['error', 'prefer-single'],
        'style/jsx-self-closing-comp': 'error',
        'style/jsx-tag-spacing': ['error', { beforeClosing: 'always' }],
        'style/key-spacing': 'error',
        'style/keyword-spacing': 'error',
        'style/member-delimiter-style': 'error',
        'style/no-extra-semi': 'error',
        'style/no-multi-spaces': 'error',
        'style/no-tabs': 'warn',
        'style/no-trailing-spaces': 'error',
        'style/no-whitespace-before-property': 'error',
        'style/object-curly-spacing': ['error', 'always'],
        'style/object-property-newline': 'error',
        'style/operator-linebreak': ['error', 'before'],
        'style/quote-props': ['error', 'consistent-as-needed'],
        'style/quotes': ['error', 'single'],
        'style/rest-spread-spacing': ['error', 'never'],
        'style/semi': 'error',
        'style/semi-spacing': 'error',
        'style/semi-style': 'error',
        'style/space-before-blocks': ['error', 'always'],
        'style/space-before-function-paren': 'error',
        'style/space-unary-ops': 'error',
        'style/switch-colon-spacing': 'error',
        'style/type-annotation-spacing': 'error',
        'style/type-generic-spacing': 'error',
        'style/type-named-tuple-spacing': 'error',
        'style/yield-star-spacing': ['error', { before: true,
          after: false }],
      },
    },
  ];
}
