name: Release

concurrency:
  group: release
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Override version'
        required: false
        type: string
      dry_run:
        description: 'Whether to perform a dry run'
        required: true
        default: true
        type: boolean
      first_release:
        description: 'Whether at least 1 package is being released for the first time'
        required: true
        default: false
        type: boolean

jobs:
  release:
    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: '.node-version'
          cache: pnpm

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Release and publish
        run: |
          pnpm run release --verbose \
            --version=${{ inputs.version }} \
            --dry-run=${{ inputs.dry_run }} \
            --first-release=${{ inputs.first_release }}
        env:
          NPM_CONFIG_PROVENANCE: true
